### ISSUE TITLE
CONFIG.MD has wrong format for many command line arguments

### ISSUE THREAD

**Issue by Greelan** [teamspeak/teamspeak6-server#9]
For example, it lists:

`--accept-license 0`

However, the server reports "unexpected argument 0"

It seems that on a lot of the boolean settings (and maybe others like in #16 ), a space is not valid, only an equals sign, eg:

`--accept-license=0`

**Comment by achimklittich** [comment]
We've updated the README.md and CONFIG.md to clarify usage.

Note: `--accept-license` works as a standalone flag; no value is required. Using a value like `--accept-license 0` will not work and cause failure.

If you prefer to provide a value explicitly (e.g., --accept-license=0), please note that this form is currently undocumented in CONFIG.md, but still supported.

**Comment by Greelan** [comment]
That still doesn't seem to address the underlying issue, that spaces between keys and values on the command line don't appear to work reliably, and an equals sign is needed. See eg #16.  Even your own response uses an equals sign

**Comment by achimklittich** [comment]
We’ve confirmed that non-boolean flags work as expected when the key and value are separated by a space. Boolean flags, on the other hand, are currently supported in two forms: either by specifying the flag on its own (e.g., `--flag`) or by using the equal sign syntax you discovered (e.g., `--flag=true`).

The ticket you referenced seems to be a special case, as the flag in question is only recognized during the server's initial startup.

At present, the server supports boolean flags without requiring an explicit value. Given the binary nature of boolean options, the presence or absence of the flag itself is generally sufficient to configure the desired behavior.
